# Generated by Django 2.1.5 on 2019-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225, unique=True)),
                ('emil', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('role', models.CharField(default='user', max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
